/*
 * File: app/store/LearningObject.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cookbool_yPBL.store.LearningObject', {
    extend: 'Ext.data.Store',

    requires: [
        'Cookbool_yPBL.model.LearningObject'
    ],

    config: {
        autoLoad: true,
        model: 'Cookbool_yPBL.model.LearningObject',
        storeId: 'LearningObject',
        proxy: {
            type: 'ajax',
            url: 'resources/json/learningobjects.json',
            reader: {
                type: 'json'
            }
        }
    }
});