/*
 * File: app/view/LearningObjectList.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cookbool_yPBL.view.LearningObjectList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.learningObjectList',

    config: {
        itemId: 'learningObjectList',
        store: 'LearningObject',
        onItemDisclosure: true,
        itemTpl: [
            '<h2>{id} {title}</h2>',
            '<div>{date:date("M d, Y")}</div>',
            '<img src="{ranking_img_url_small}"/></br>',
            '<div>{description}</div>'
        ]
    }

});