/*
 * File: app/model/FeedBack.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cookbool_yPBL.model.FeedBack', {
    extend: 'Ext.data.Model',

    uses: [
        'Cookbool_yPBL.model.LearningObject',
        'Cookbool_yPBL.model.User'
    ],

    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'learningObjectId'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'comment'
            },
            {
                name: 'rank'
            },
            {
                name: 'rank_img_url_small'
            },
            {
                dateFormat: 'Y-m-d',
                name: 'date',
                type: 'date'
            }
        ],
        belongsTo: [
            {
                model: 'Cookbool_yPBL.model.LearningObject'
            },
            {
                model: 'Cookbool_yPBL.model.User'
            }
        ]
    }
});