/*
 * File: app/model/LearningObject.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Cookbool_yPBL.model.LearningObject', {
    extend: 'Ext.data.Model',
    uses: [
        'Cookbool_yPBL.model.FeedBack'
    ],
    config: {
        fields: [
            {
                name: 'id'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                dateFormat: 'Y-m-d',
                name: 'dateCreation',
                type: 'date'
            },
            {
                name: 'description'
            },
            {
                name: 'rating_img_url_small'
            }
        ],
        hasMany: {
            model: 'Cookbool_yPBL.model.FeedBack',
            name: 'feedbacks'
        }
    }
});